### ISSUE TITLE
Editor: Shortcuts not working on non-QWERTY keyboards/layouts

### ISSUE THREAD

**Issue by marconett** [defold/defold#5047]
**Describe the bug**
Shortcuts not working on non-QWERTY keyboards and/or layouts (I am not too sure, as I only tested the below use-case).

There's similar issues that probably all boil down to the same problem (see related issues).

This makes the Editor very much unusable for anyone using a non-QWERTY style keyboard. It seems to be a problem on at least macOS and Windows.

Looking at other projects (https://github.com/FXMisc/RichTextFX/pull/801) it doesn't look like it's very hard to fix. I'd love to contribute to this somehow, but having never touched either Closure or JavaFX, it's very daunting.

**To Reproduce**
- Have a german keyboard on macOS
- Press cmd+z to try to undo something in the editor

Result: The edit-item in the menubar flashes as if it would have done something, but the editor does not undo the the text.

Switching my macOS keyboard layout to English also does not fix the issue.

**Workaround**
- Undoing using the menu works.
- Undoing with cmd+y works (the z and y buttons are swapped on a german keyboard compared to a us keyboard).

**Defold version (REQUIRED):**
  - Version 1.2.171

**Additional context (OPTIONAL):**
Maybe looking for [JDK-8090257](https://bugs.openjdk.java.net/browse/JDK-8090257) workarounds in other JavaFX projects is worth a try: https://github.com/FXMisc/RichTextFX/issues/799

Related to: https://github.com/defold/editor2-issues/issues/1236 https://github.com/defold/editor2-issues/issues/1597 https://github.com/defold/editor2-issues/issues/2190 https://github.com/defold/editor2-issues/issues/2156 https://github.com/defold/editor2-issues/issues/2844

Previous issue: https://github.com/defold/editor2-issues/issues/2725

**Comment by britzl** [comment]
Thank you for the bug report. I believe we already have something similar in the backlog. The workarounds are definitely worth looking into!

**Comment by britzl** [comment]
https://github.com/defold/defold/issues/5021

**Comment by britzl** [comment]
@marconett have you tried playing with the new configurable keybindings to solve problems with non-QWERTY keyboards?

https://defold.com/manuals/editor/#customizing-shortcuts

**Comment by beldenfox** [comment]
I've been digging around in the JavaFX sources for the last few days and running some tests. With the existing JavaFX accelerator machinery the solution is to update the Mac accelerator strings by changing the characters to lower case and surrounding them with single quotes e.g.  from `Meta+A` to `Meta+'a'`. I've tested this by altering `keymap.clj` to use `Meta-'z'` and verified that it works. I haven't tested external keybinding files but anything that goes through `KeyCombination.KeyCombination(String)` should behave the same way.

The problem is due to deep weirdness in multiple areas of Mac-specific code. Without the single quotes JavaFX uses a `KeyCodeCombination` and the Java key code mapping on Mac is broken. With the single quotes you end up with a `KeyCharacterCombination` which on the Mac goes through some internal pathways where two wrongs to make a right. I can't seem to find a better solution using the public JavaFX API's.

BTW, if you're testing this you might find that the accelerator string `Meta-'Z'` (with a capital letter) sometimes works. Namely, it will work if you've typed a capital `Z` somewhere before trying to invoke the accelerator. `Meta-'z'` is more reliable.

**Comment by britzl** [comment]
That's some good research done! It's there a change that you recommend we should do?

**Comment by beldenfox** [comment]
Yes, sweep through keymap.clj and in the Mac-specific section change every accelerator string of the form `Meta+` or `Shift+Meta+` followed by a capital letter. Change the letter to lowercase and surround it in single quotes e.g. change `Meta+A` to `Meta+'a'`, `Shift+Meta+Z` to `Shift+Meta+'z'`, etc. Based on my understanding of the JavaFX code and my own testing you're better off leaving any string involving `Alt` or `Ctrl` as-is.

This is one of those changes which will take a few minutes to implement and a long time to test, you might consider publishing a keybindings file with these changes for users to try out.

**Comment by beldenfox** [comment]
FYI, I submitted a PR to fix this (openjdk/jfx#425). The JavaFX folks haven't done any substantial work in keyboard handling for several years so it will take a while for everyone to come up to speed and get this reviewed. It should be easy to back port this to earlier versions of JavaFX if you're running with your own custom build.

**Comment by vlaaad** [comment]
Damn, even with KeyCharacterCombinations this behaves super weird. For example, I tried using `Meta+'/'` instead of `Meta+Slash` in the editor keymap.

When using `'/'`:
- With Russian layout, <kbd>Meta + Slash</kbd> does not work, <kbd>Meta + |</kbd>  does not work, then starts working after I type forward slash by pressing <kbd>Shift+|</kbd> (which produces forward slash)
- With Swedish layout, <kbd>Meta Slash</kbd> initially works, then I type <kbd>Slash</kbd> and it inserts `_`, the I type <kbd>Shift 7</kbd>, it inserts `/`, then <kbd>Meta 7</kbd> starts to work and <kbd>Meta Slash</kbd> does not.

It looks like the key handling is unfathomably cursed, and KeyCharacter combos don't really help here. I'm holding my fingers crossed for https://github.com/openjdk/jfx/pull/425.

**Comment by beldenfox** [comment]
Ouch. I should have re-visited this thread a long time ago and saved you the trouble. Key handling on the Mac is indeed cursed across the board.

@vlaaad Which Russian layout are you using? From what you describe it looks like `Russian - PC` but I just want to be sure.

A quick summary: in a perfect world you would use KeyCharacterCombinations for accelerators involving punctuation and symbols  (like `Meta+'/'`, `Meta+'+'`, and `Meta+','`) and KeyCodeCombinations for everything else. You should probably stick with those guidelines and wait for the JavaFX bugs to get fixed.

openjdk/jfx#425 will fix KeyCode combos so `Meta+Z` will be where users expect it. It will not fix KeyCharacter combos so `Meta+'/'` will still exhibit cursed behavior. Once openjdk/jfx#425 is integrated I'll try to get KeyCharacters working ASAP. The long-term solution begins with openjdk/jfx#694 but I might be able to get a short-term patch in place faster.

As for the weird behavior you're seeing, the implementation of KeyCharacter combos requires mapping backward from a character to a physical key. There's no API to do this on the Mac so instead the code monitors your keystrokes to learn the association between keys and characters. So, yes, sometimes you have to type the character before the accelerator starts working. And it only remembers one association for any given character so if you type a character on the numeric keypad it will forget all about it on the main keyboard.

BTW, KeyCharacter combos also have problems on Linux and Windows though not quite so severe. Probably the biggest is that they just don't work on the numeric keypad. openjdk/jfx#694 also addresses that.

**Comment by vlaaad** [comment]
Yes, I use `Russian - PC`. Many thanks for doing this work on key handling in JavaFX!

**Comment by beldenfox** [comment]
@britzl I am not optimistic about getting Linux fixed any time soon. I'm having a difficult time getting keyboard related PR's reviewed (openjdk/jfx#425 literally took years) and Linux is particularly tough. There's no one on the core JavaFX team that understands the Gdk API well and the documentation for it is just wretched. Currently I'm focusing on getting Windows fixed (openjdk/jfx#1126) and then Mac. It doesn't help that to enable testing of Linux I have to get the Robot code fixed which is yet another PR involving Gdk that is languishing (openjdk/jfx#718).

**Comment by britzl** [comment]
Ouch. I understand. It sounds like a nightmare... Incremental improvements per platform might be the way to go then!

**Comment by AGulev** [comment]
It seems like the PR with a fix was merged into JavaFX. But the version of JavaFX with the fix (22+18) wasn't released on Maven =/

**Comment by beldenfox** [comment]
The recent PR triggered a nasty Apple bug on macOS 13 and earlier. A new PR was just merged that gets around this problem (openjdk/jfx#1295).

I've managed to clear up most of the shortcut issues on Mac and Windows for JavaFX 22. Right now the Ctrl+'+' shortcut still doesn't work with the numeric keypad on Windows. There is a PR for this (openjdk/jfx#1289) but it has not seen any review cycles. I'll be submitting Linux fixes in mid-December but I doubt they'll make it into 22.

The Maven build for JavaFX is broken. There's some discussion on the openjfx-dev@openjdk.org mailing list as well as PR openjdk/jfx#1232. Not an area I'm familiar with so all I can do is give you pointers

**Comment by AGulev** [comment]
Works now, Thank you @beldenfox !!!
https://github.com/defold/defold/assets/2209596/a3ec610f-a5c4-4c9a-af2c-155dda7bafba
