### ISSUE TITLE
Build fails with internal server error(bob/editor)

### ISSUE THREAD

**Issue by SalavatR** [defold/defold#7658]
**Describe the bug (REQUIRED)**
bob fails with ios error

Command

```
java -jar $(BOB_FILE) \
    --settings game.project \
    --bundle-output dist \
    --build-report-html build/report.html \
    --variant debug \
    --archive \
    --architectures arm64-ios, x86_64-ios \
    --platform arm64-ios \
    --with-symbols \
    resolve clean distclean build bundle
```

Error:
```
'arm64-ios' could not be built. Sdk version: 'f5e114aaebe25c5242db5f0066af2f5189c09f99'
Log: 'Internal Server Error'
Cause: com.defold.extender.client.ExtenderClientException: Failed to build source.

```

**Defold version (REQUIRED):**
  - Version 1.4.4, 1.4.5, 1.4.6-beta

**Platforms (REQUIRED):**
 - Platforms: iOS, android
 - OS: MacOs
 - Device: MacbookPro m1 2021

**Comment by SalavatR** [comment]
Android now works

**Comment by SalavatR** [comment]
Same problem in editor macos

**Comment by SalavatR** [comment]
<img width="277" alt="image" src="https://github.com/defold/defold/assets/11291477/543a72cf-9188-4e34-a727-4e5dee99e857">
https://github.com/britzl/defold-clipboard/archive/refs/tags/1.3.0.zip

**Comment by JCash** [comment]
Thanks for the info!

Which extensions are you using?

**Comment by SalavatR** [comment]
Not only, here is full list

dependencies#0 = https://github.com/Insality/druid/archive/refs/tags/0.10.3.zip
dependencies#1 = https://github.com/britzl/monarch/archive/refs/tags/3.7.0.zip
dependencies#2 = https://github.com/britzl/ludobits/archive/refs/tags/7.2.0.zip
dependencies#3 = https://github.com/britzl/defold-input/archive/2.8.5.zip
dependencies#4 = https://github.com/britzl/defold-metrics/archive/1.2.1.zip
dependencies#5 = https://github.com/britzl/defold-orthographic/archive/refs/tags/3.2.1.zip
dependencies#6 = https://github.com/britzl/defold-clipboard/archive/refs/tags/1.3.0.zip
dependencies#7 = https://github.com/Melsoft-Games/defold-protobuf/archive/0e5d3b2.zip
dependencies#8 = https://github.com/defold/extension-spine/archive/refs/tags/2.10.3.zip
dependencies#9 = https://github.com/defold/extension-iap/archive/refs/tags/5.0.1.zip
dependencies#10 = https://github.com/defold/extension-adinfo/archive/refs/tags/3.0.1.zip
dependencies#11 = https://github.com/indiesoftby/defold-sentinel/archive/refs/tags/1.1.0.zip
dependencies#12 = https://github.com/HGPoint/defold-maxsdk/archive/refs/tags/11.8.2.0.zip
dependencies#13 = https://github.com/SalavatR/def_appsflyer_ad_revenue/archive/refs/tags/6.9.0.zip
dependencies#14 = https://github.com/HGPoint/defold-extension-appsflyer/archive/refs/tags/6.10.2.zip
dependencies#15 = https://github.com/SalavatR/extension-firebase-analytics/archive/refs/tags/2.2.2.zip
dependencies#16 = https://github.com/SalavatR/extension-firebase/archive/refs/tags/1.3.1.zip
dependencies#17 = https://github.com/defold/extension-push/archive/refs/tags/4.0.0.zip
dependencies#18 = https://github.com/HGPoint/def_ios_storage/archive/refs/tags/0.0.3.zip



today i tried to migrate max sdk to cocoapods
after this, problems began

here is dependencies
    pod 'AppLovinSDK'
    pod 'AppLovinMediationAdColonyAdapter'
    pod 'AppLovinMediationGoogleAdManagerAdapter'
    pod 'AppLovinMediationGoogleAdapter'
    pod 'AppLovinMediationInMobiAdapter'
    pod 'AppLovinMediationIronSourceAdapter'
    pod 'AppLovinMediationVungleAdapter'
    pod 'AppLovinMediationMaioAdapter'
    pod 'AppLovinMediationFacebookAdapter'
    pod 'AppLovinMediationMintegralAdapter'
    pod 'AppLovinMediationMyTargetAdapter'
    pod 'AppLovinMediationUnityAdsAdapter'

**Comment by JCash** [comment]
@SalavatR I just did a fix on the server (and it now works for us again).
Could you please try again?

**Comment by SalavatR** [comment]
@JCash 
with cocoapods too?

**Comment by JCash** [comment]
well, yes, a regular build?

The server should be fine now.

**Comment by SalavatR** [comment]
regular build fails
ERROR: unspecified:-1: 'com.dynamo.bob.CompileExceptionError: 'arm64-ios' could not be built. Sdk version: 'f5e114aaebe25c5242db5f0066af2f5189c09f99'
Log: 'Internal Server Error''

'arm64-ios' could not be built. Sdk version: 'f5e114aaebe25c5242db5f0066af2f5189c09f99'
Log: 'Internal Server Error'
Cause: com.defold.extender.client.ExtenderClientException: Failed to build source.

**Comment by SalavatR** [comment]
editor works

**Comment by SalavatR** [comment]
regular bob build success

build with pods fail

pod 'AppLovinSDK'
pod 'AppLovinMediationAdColonyAdapter'
pod 'AppLovinMediationGoogleAdManagerAdapter'
pod 'AppLovinMediationGoogleAdapter'
pod 'AppLovinMediationInMobiAdapter'
pod 'AppLovinMediationIronSourceAdapter'
pod 'AppLovinMediationVungleAdapter'
pod 'AppLovinMediationMaioAdapter'
pod 'AppLovinMediationFacebookAdapter'
pod 'AppLovinMediationMintegralAdapter'
pod 'AppLovinMediationMyTargetAdapter'
pod 'AppLovinMediationUnityAdsAdapter'


Client error when building engine remotely: Failed to resolve CocoaPod dependencies. /var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/job15508857022694156580/CocoaPodsService/Pods/AppLovinMediationGoogleAdManagerAdapter/AppLovinMediationGoogleAdManagerAdapter-10.4.0.0/AppLovinMediationGoogleAdManagerAdapter.xcframework/ios-arm64_armv7/AppLovinMediationGoogleAdManagerAdapter.framework -> /var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/job15508857022694156580/CocoaPodsService/frameworks/lib/arm64-ios/AppLovinMediationGoogleAdManagerAdapter.framework

**Comment by britzl** [comment]
@SalavatR can you share a link to the repo with the dependency you have troubles with? Which version of bob are you using? And which build server (build.defold.com or build-stage.defold.com)?

**Comment by SalavatR** [comment]
@britzl 
here it
https://github.com/HGPoint/defold-maxsdk/tree/pod_file
https://github.com/HGPoint/defold-maxsdk/archive/refs/tags/11.8.2.1_pod.zip

**Comment by SalavatR** [comment]
i think we extend pod file to more networks


    pod 'AppLovinSDK'
    pod 'AppLovinMediationAdColonyAdapter'
    pod 'AppLovinMediationAmazonAdMarketplaceAdapter'
    pod 'AmazonPublisherServicesSDK'
    pod 'AppLovinMediationBidMachineAdapter'
    pod 'AppLovinMediationChartboostAdapter'
    pod 'AppLovinMediationCriteoAdapter'
    pod 'AppLovinMediationCSJAdapter'
    pod 'AppLovinMediationFyberAdapter'
    pod 'AppLovinMediationGoogleAdManagerAdapter'
    pod 'AppLovinMediationGoogleAdapter'
    pod 'AppLovinMediationHyprMXAdapter'
    pod 'AppLovinMediationInMobiAdapter'
    pod 'AppLovinMediationIronSourceAdapter'
    pod 'AppLovinMediationVungleAdapter'
    pod 'AppLovinMediationLineAdapter'
    pod 'AppLovinMediationMaioAdapter'
    pod 'AppLovinMediationFacebookAdapter'
    pod 'AppLovinMediationMintegralAdapter'
    pod 'AppLovinMediationMobileFuseAdapter'
    pod 'AppLovinMediationMyTargetAdapter'
    pod 'AppLovinMediationNendAdapter'
    pod 'AppLovinMediationOguryPresageAdapter'
    pod 'AppLovinMediationByteDanceAdapter'
    pod 'AppLovinMediationSmaatoAdapter'
    pod 'AppLovinMediationTapjoyAdapter'
    pod 'AppLovinMediationTencentGDTAdapter'
    pod 'AppLovinMediationUnityAdsAdapter'
    pod 'AppLovinMediationVerveAdapter'
    pod 'AppLovinMediationYandexAdapter'

**Comment by britzl** [comment]
> @britzl here it https://github.com/HGPoint/defold-maxsdk/tree/pod_file https://github.com/HGPoint/defold-maxsdk/archive/refs/tags/11.8.2.1_pod.zip

Thanks. I'll take a look.

**Comment by SalavatR** [comment]
Great news!

**Comment by britzl** [comment]
> Update: The issue was that the `AppLovinMediationAdColonyAdapter` had an xcframework with a static library in it (.a file). The extender server only expected to encounter `*.frameworks` inside the xcframework. I'm working on a fix for this (we also have to link the static library).

This should be fixed in https://github.com/defold/extender/commit/c7a1feb3cedca2c70dd889ed0f33d70952d950d9

This fix has been deployed to build-stage.defold.com which handles the static library. Please give it a try!

> Also I noticed that the AdColony pod contains a `AppLovinSDKResources.bundle` which we currently ignore. This bundle contains storyboards and other resource files. We should send such packages back to the client and include them in the bundle. This way you don't have to manually add this in your `extension/res/ios` folder.

Still being worked on: https://github.com/defold/extender/issues/292

**Comment by britzl** [comment]
I don't see an error in log.txt?

**Comment by SalavatR** [comment]
Yes, that full log, without error, I'll try tomorrow to clear cache, and
build again

пт, 19 мая 2023 г., 19:20 Björn Ritzl ***@***.***>:

**Comment by SalavatR** [comment]
Oops, my bad!
wrong build server, should be 
	--build-server https://build-stage.defold.com 

also `*.a` files from frameworks should be copied to lib/ios directory manually now, or it won't work

and extender doesn't resolve dependencies for pod 'AppLovinMediationByteDanceAdapter', and i can't resolve it manualy, maybe because of `.a` files and headers files

**Comment by AGulev** [comment]
> Oops, my bad!
> 
> wrong build server, should be 
> 
> 	--build-server https://build-stage.defold.com 
> 
> 
> 
> also `*.a` files from frameworks should be copied to lib/ios directory manually now, or it won't work
> 
> 
> 
> and extender doesn't resolve dependencies for pod 'AppLovinMediationByteDanceAdapter', and i can't resolve it manualy, maybe because of `.a` files and headers files

I think it should be tested using the latest alpha (maybe beta, @britrl ?)

**Comment by SalavatR** [comment]
one more error, if i set version for amazon and amazon adapter build fails 

pod 'AppLovinMediationAmazonAdMarketplaceAdapter', '4.7.1.0'
pod 'AmazonPublisherServicesSDK', '4.7.1'

[log.txt](https://github.com/defold/defold/files/11524590/log.txt)

**Comment by britzl** [comment]
> also `*.a` files from frameworks should be copied to lib/ios directory manually now, or it won't work

Hmm, no, that can't be right. The .a file is a static library and the code should be linked into the main binary on the build server. If that is not working as expected there is another issue we need to look into with regard to linking these libraries.

> and extender doesn't resolve dependencies for pod 'AppLovinMediationByteDanceAdapter', and i can't resolve it manualy, maybe because of `.a` files and headers files

Do you get an error or something?

**Comment by SalavatR** [comment]
> Hmm, no, that can't be right. The .a file is a static library and the code should be linked into the main binary on the build server. If that is not working as expected there is another issue we need to look into with regard to linking these libraries.

applovin sdk doesn't find this adapters in build, without errors, because this is not necessary dependencies for sdk work, but when i add them manually everything works like a charm


> > and extender doesn't resolve dependencies for pod 'AppLovinMediationByteDanceAdapter', and i can't resolve it manualy, maybe because of .a files and headers files
>
> Do you get an error or something?

if i have  https://github.com/britzl/defold-clipboard/archive/refs/tags/1.3.0.zip in my dependencies list i got error:

> ERROR: clipboard/ext.manifest:1: 'symbol(s) not found for architecture arm64'
> 
> 
> ERROR: clipboard/ext.manifest:1: 'Undefined symbols for architecture arm64:
>   "_NSStringFromPAGAdEnumItem", referenced from:
>       +[PAGTrackerHelper trackTagWithAdType:interactionType:ignore

Landscape:] in PAGAdSDK(PAGTrackerHelper.o)'

if i remove clipboard from deps list, i got this

> 
> ERROR: def_applovin_maxsdk/ext.manifest:1: 'symbol(s) not found for architecture arm64'
> 
> ERROR: def_applovin_maxsdk/ext.manifest:1: 'Undefined symbols for architecture arm64:
>   "_NSStringFromPAGAdEnumItem", referenced from:
>       +[PAGTrackerHelper trackTagWithAdType:interactionType:ignoreLandscape:] in PAGAdSDK(PAGTrackerHelper.o)'
>

**Comment by britzl** [comment]
@SalavatR I believe this issue should be fixed now with the latest release of the build servers.
